/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */

    indexSidebar: [
        //'index'
    ],

    chewbotccaSidebar: [
        'bots/discord/chewbotcca',
        {
            type: 'category',
            label: 'Commands',
            link: {
                type: 'doc',
                id: 'bots/discord/chewbotcca/commands',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'bots/discord/chewbotcca/commands',
                }
            ]
        }
    ],

    mlbSidebar: [
        'bots/discord/mlb-game-feed',
        'bots/discord/mlb-game-feed/watching-a-game-feed',
        {
            type: 'category',
            label: 'Commands',
            link: {
                type: 'doc',
                id: 'bots/discord/mlb-game-feed/commands',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'bots/discord/mlb-game-feed/commands',
                }
            ]
        }
    ]
};

module.exports = sidebars;
